export const columns = [
  { field: "second_name", label: "Name" },
  { field: "team", label: "Team" },
  { field: "now_cost", label: "Cost" },
  { field: "total_points", label: "Total Points" },
  { field: "goals_scored", label: "Goals Scored" },
  { field: "assists", label: "Assists" },
  { field: "minutes", label: "Minutes" },
  { field: "bonus", label: "Bonus Points" },
  { field: "influence", label: "Influence" },
  { field: "creativity", label: "Creativity" },
  { field: "threat", label: "Threat" },
  { field: "expected_goals", label: "Expected Goals" },
  { field: "expected_assists", label: "Expected Assists" },
  { field: "expected_goal_involvements", label: "Expected Goal Involvements" },
  { field: "expected_goals_conceded", label: "Expected Goals Conceded" },
];

export const availableFields = [
  // { value: "team", label: "Team" },
  { value: "total_points", label: "Total Points" },
  { value: "now_cost", label: "Cost" },
  { value: "goals_scored", label: "Goals Scored" },
  { value: "assists", label: "Assists" },
  { value: "minutes", label: "Minutes" },
  { value: "bonus", label: "Bonus Points" },
  { value: "influence", label: "Influence" },
  { value: "creativity", label: "Creativity" },
  { value: "threat", label: "Threat" },
  { value: "expected_goals", label: "Expected Goals" },
  { value: "expected_assists", label: "Expected Assists" },
  { value: "expected_goal_involvements", label: "Expected Goal Involvements" },
  { value: "expected_goals_conceded", label: "Expected Goals Conceded" },
  { value: "points_per_game", label: "Points Per Game" },
  { value: "expected_assists_per_90", label: "Expected Assists per 90" },
  { value: "expected_goals_per_90", label: "Expected Goals per 90" },
  {
    value: "expected_goal_involvements_per_90",
    label: "Expected Goals Involvements per 90",
  },
  { value: "selected_by_percent", label: "Selected by Percent" },
  { value: "form", label: "Form" },
  { value: "clean_sheets_per_90", label: "Clean Sheet per 90" },
];
